'use strict';

var buildController = require('../controllers/build');

module.exports = function() {
  return [
    {
      method: 'POST',
      path: '/build',
      handler: buildController.insert,
      config: {
        description: 'Creates a new build record',
        notes: 'This method will be called at the end of the publish to store step in TeamCity',
        validate: {
          payload: {
            buildId: Joi.string().description('The build Id as generated by TeamCity, e.g. 5.2.1209'),
            branch: Joi.string().description('The branch on which the build ran, e.g. develop')
          }
        }
      }
    },
    {
      method: 'GET',
      path: '/build/{id}',
      handler: buildController.findById
    },
    {
      method: 'GET',
      path: '/build',
      handler: buildController.query
    }
  ];
}();
